### ISSUE TITLE
Cut, Copy & Paste: Open Source collaboration workshops (without digital tools!)

### ISSUE THREAD

**Issue by cameralibre** [acabunoc/open-leadership-zone#1]
Thanks for submitting your project to be featured in the Open Leadership Zone at [MozFest 2017](http://mozillafestival.org/) :sparkles:

This is open to any project in [Mozilla Open Leaders round 4](https://mozilla.github.io/leadership-training/round-4/projects/) -- even if you're not coming to MozFest. This process ensures that you're following open practices and will help set you up for a sustained contributor community afterwards. If you have any questions, feel free to reach out to @acabunoc or ask questions in our [chat room](http://gitter.im/mozilla/open-leadership-training).

## Open Project Checklist :clipboard:
Your project must complete the following to be a featured on [Mozilla Pulse](http://mozillapulse.org/) and the Open Leadership Zone at MozFest 2017. As you complete each exercise, check off the box and comment with a link to your completed resource. This [template repository](https://github.com/acabunoc/mozfest-repo-template) is here to help you if you get stuck!

- [x] Complete [Open Leadership 101](https://mozilla.teachable.com/p/open-leadership-101)
- [x] Provide a GitHub repository for work and discussion on your project in a comment
  * new to GitHub?  Here's a [step-by-step guide on using the #mozfest template](https://docs.google.com/document/d/e/2PACX-1vTUfSHQvqME7Z58WgUOfRogc7fcSKpxivTm0HSDWq6qFjIFyV8UNdBzphoZlCh4QTbx1ckpmzTQV6ax/pub#h.xx0csqfdsayz)
- [x] [Create file: README.md](https://mozilla.github.io/open-leadership-training-series/articles/opening-your-project/write-a-great-project-readme/) in your project repository. This file should help newcomers understand what your project is, why it's important, and kinds of help you're looking for.
- [x] [Create file: LICENSE](http://choosealicense.com/) to give your project an open license, allowing for sharing and remixing.
- [x] [Create file: CONTRIBUTING.md](https://mozilla.github.io/open-leadership-training-series/articles/building-communities-of-contributors/write-contributor-guidelines/) so others know how they can contribute. If you'd like, you can [remix this template](https://github.com/acabunoc/mozfest-repo-template/blob/master/CONTRIBUTING.md)
- [x] [Create file: CODE_OF_CONDUCT.md](https://mozilla.github.io/open-leadership-training-series/articles/building-communities-of-contributors/write-a-code-of-conduct/). This can be the [Mozilla Community Participation Guidelines](https://www.mozilla.org/en-US/about/governance/policies/participation/) or a code of conduct of your choice
- [x] Turn on your [Issue Tracker](https://docs.google.com/document/d/e/2PACX-1vTUfSHQvqME7Z58WgUOfRogc7fcSKpxivTm0HSDWq6qFjIFyV8UNdBzphoZlCh4QTbx1ckpmzTQV6ax/pub#h.ay6inrqrank7) and [create issues](https://docs.google.com/document/d/e/2PACX-1vTUfSHQvqME7Z58WgUOfRogc7fcSKpxivTm0HSDWq6qFjIFyV8UNdBzphoZlCh4QTbx1ckpmzTQV6ax/pub#h.sb4dv3al8i8a) to describe each task that you need help with and how a contributor can get started on that task. If you're participating in [Hacktoberfest](http://hacktoberfest.digitalocean.com/), [Create a label](https://docs.google.com/document/d/e/2PACX-1vTUfSHQvqME7Z58WgUOfRogc7fcSKpxivTm0HSDWq6qFjIFyV8UNdBzphoZlCh4QTbx1ckpmzTQV6ax/pub#h.ah0e4pnoebnc) called `hacktoberfest` and apply it to your issues.

## Ready to be featured :tada:
- [x] [Fill out this form](https://www.mozillapulse.org/add) to submit your project to Mozilla Pulse. Add the tag `open leadership zone`.
- [x] Leave a comment on this issue with the text `This is ready for the Open Leadership Zone`. @acabunoc will review this issue. If accepted, your project will be approved on Mozilla Pulse and featured in the Open Leadership Zone.

If you get stuck at any point, feel free to look at the [project templates](https://docs.google.com/document/d/e/2PACX-1vTUfSHQvqME7Z58WgUOfRogc7fcSKpxivTm0HSDWq6qFjIFyV8UNdBzphoZlCh4QTbx1ckpmzTQV6ax/pub#h.xx0csqfdsayz) or reach out to your mentor or @acabunoc. We're here to help you through this process.

**Comment by cameralibre** [comment]
Hi @acabunoc , can I make a suggestion?
It would be great if Mozilla Open Leadership focused less on Github as '_the place_ for open projects' and spoke more of it as '_an example of_ a space for open projects'. 

My project is not on Github, but rather on [Gitlab](https://gitlab.com/cameralibre/cut-copy-and-paste), and I would like to keep it there if possible. Let me know if that's ok!

...in case you're curious _why_ I prefer Gitlab:
- I prefer the interface & design of GitLab, and I personally find it easier to use than GitHub
- I like GitLab's values and believe it to be [ethically & transparently operated](https://about.gitlab.com/about/#values)
- GitLab's core software is Free/Libre Open Source Software (unlike GitHub - although they do release many other tools as open source). When building projects in the commons, I like to use open source tools, especially if they're on par with, or if I find them better than proprietary alternatives. I'm particularly averse to centralizing resources and tasking a for-profit company with stewarding the whole open source ecosystem, and am wary of GitHub's growing influence and importance. GitLab's open source aspect simply gives me a higher level of trust in them - but I wouldn't want them to have a monopoly either!
- I'm not currently self-hosting the Gitlab repo, but that would be a step I'd like to take as the project grows, and I'd like to take all issues and history with me. That way I can easily adapt it to suit my needs, I can make it feel like home, and integrate it with the other tools I use. I don't think that is possible with GitHub. 
- By using F/LOSS infrastructure, when I engage with the software developers, bring new use cases to their attention, submit bug reports, or contribute in other ways, I help grow the commons. If nobody uses the F/LOSS solutions, they can't improve, and the proprietary options gradually become the only options.
- Any open source project (such as mine, or the Mozilla Open Leadership program) is prototyping and improving the working methods which future projects will adopt and learn from. When people ask me for advice about setting up infrastructure, I'm glad that I can say: _"well, for my work, I use Discourse, NextCloud, Wordpress and Gitlab. You can see if you like them, download them for free and install them yourself, or you can contact [service provider] and get it set up for you."_ I feel secure knowing that they won't be locked in to a particular website, or even to a particular hosting provider, and (at least in my mind) they are therefore more sustainable and scalable as a project in the long-term.

I hope that makes sense, and if you have any questions, let me know!

**Comment by acabunoc** [comment]
Hey Sam!

We focus on GitHub for two reasons:
1. It's required for participation in Hacktoberfest
2. We only provide training materials for GitHub

If you're comfortable on GitLab and won't be participating in Hacktoberfest, that's fine!

**Comment by cameralibre** [comment]
>  If you're comfortable on GitLab and won't be participating in Hacktoberfest, that's fine!

Great, thanks :)

Just to clarify, my issue isn't that you're using Github or teaching people to use it - it's just a matter of language & communication, and ensuring that people understand that there are a whole range of different methods and sites that they can use to run an open project - these concepts (contributing guide, Code of Conduct etc) are universal and can be implemented anywhere, whether on a Discourse, Bitbucket, Loomio, Scuttlebutt, in person events, mailing list.... but that the focus and examples for this course will take place on Github.

**Comment by cameralibre** [comment]
This is ready for the Open Leadership Zone

**Comment by acabunoc** [comment]
Your project is featured! https://www.mozillapulse.org/entry/463 🎉 

Nice to see you have a few events coming up to test this at :)
