### ISSUE TITLE
Thalos: simple and secure approach to file storage in untrusted environments

### ISSUE THREAD

**Issue by ecleipteon** [acabunoc/open-leadership-zone#2]
Thanks for submitting your project to be featured in the Open Leadership Zone at [MozFest 2017](http://mozillafestival.org/) :sparkles:

This is open to any project in [Mozilla Open Leaders round 4](https://mozilla.github.io/leadership-training/round-4/projects/) -- even if you're not coming to MozFest. This process ensures that you're following open practices and will help set you up for a sustained contributor community afterwards. If you have any questions, feel free to reach out to @acabunoc or ask questions in our [chat room](http://gitter.im/mozilla/open-leadership-training).

## Open Project Checklist :clipboard:
Your project must complete the following to be a featured on [Mozilla Pulse](http://mozillapulse.org/) and the Open Leadership Zone at MozFest 2017. As you complete each exercise, check off the box and comment with a link to your completed resource. This [template repository](https://github.com/acabunoc/mozfest-repo-template) is here to help you if you get stuck!

- [x] Complete [Open Leadership 101](https://mozilla.teachable.com/p/open-leadership-101)
- [x] Provide a GitHub repository for work and discussion on your project in a comment
  * new to GitHub?  Here's a [step-by-step guide on using the #mozfest template](https://docs.google.com/document/d/e/2PACX-1vTUfSHQvqME7Z58WgUOfRogc7fcSKpxivTm0HSDWq6qFjIFyV8UNdBzphoZlCh4QTbx1ckpmzTQV6ax/pub#h.xx0csqfdsayz)
- [x] [Create file: README.md](https://mozilla.github.io/open-leadership-training-series/articles/opening-your-project/write-a-great-project-readme/) in your project repository. This file should help newcomers understand what your project is, why it's important, and kinds of help you're looking for.
- [x] [Create file: LICENSE](http://choosealicense.com/) to give your project an open license, allowing for sharing and remixing.
- [x] [Create file: CONTRIBUTING.md](https://mozilla.github.io/open-leadership-training-series/articles/building-communities-of-contributors/write-contributor-guidelines/) so others know how they can contribute. If you'd like, you can [remix this template](https://github.com/acabunoc/mozfest-repo-template/blob/master/CONTRIBUTING.md)
- [x] [Create file: CODE_OF_CONDUCT.md](https://mozilla.github.io/open-leadership-training-series/articles/building-communities-of-contributors/write-a-code-of-conduct/). This can be the [Mozilla Community Participation Guidelines](https://www.mozilla.org/en-US/about/governance/policies/participation/) or a code of conduct of your choice
- [x] Turn on your [Issue Tracker](https://docs.google.com/document/d/e/2PACX-1vTUfSHQvqME7Z58WgUOfRogc7fcSKpxivTm0HSDWq6qFjIFyV8UNdBzphoZlCh4QTbx1ckpmzTQV6ax/pub#h.ay6inrqrank7) and [create issues](https://docs.google.com/document/d/e/2PACX-1vTUfSHQvqME7Z58WgUOfRogc7fcSKpxivTm0HSDWq6qFjIFyV8UNdBzphoZlCh4QTbx1ckpmzTQV6ax/pub#h.sb4dv3al8i8a) to describe each task that you need help with and how a contributor can get started on that task. If you're participating in [Hacktoberfest](http://hacktoberfest.digitalocean.com/), [Create a label](https://docs.google.com/document/d/e/2PACX-1vTUfSHQvqME7Z58WgUOfRogc7fcSKpxivTm0HSDWq6qFjIFyV8UNdBzphoZlCh4QTbx1ckpmzTQV6ax/pub#h.ah0e4pnoebnc) called `hacktoberfest` and apply it to your issues.

## Ready to be featured :tada:
- [x] [Fill out this form](https://www.mozillapulse.org/add) to submit your project to Mozilla Pulse. Add the tag `open leadership zone`.
- [x] Leave a comment on this issue with the text `This is ready for the Open Leadership Zone`. @acabunoc will review this issue. If accepted, your project will be approved on Mozilla Pulse and featured in the Open Leadership Zone.

If you get stuck at any point, feel free to look at the [project templates](https://docs.google.com/document/d/e/2PACX-1vTUfSHQvqME7Z58WgUOfRogc7fcSKpxivTm0HSDWq6qFjIFyV8UNdBzphoZlCh4QTbx1ckpmzTQV6ax/pub#h.xx0csqfdsayz) or reach out to your mentor or @acabunoc. We're here to help you through this process.

**Comment by ecleipteon** [comment]
This is ready for the Open Leadership Zone.

Or it should, I guess!
Please notice me if anything is missing :)

**Comment by acabunoc** [comment]
Thanks @ecleipteon! I can add it on my end :)

**Comment by ecleipteon** [comment]
Thanks @acabunoc :)

**Comment by acabunoc** [comment]
Your project is featured!
https://www.mozillapulse.org/entry/457 🎉

**Comment by ecleipteon** [comment]
Thank you a lot!
